### ISSUE TITLE
Seperate core functions as Node.js module

### ISSUE THREAD

**Issue by 011V32** [hjdhjd/homebridge-blinds-cmd#150]
**Is your feature request related to a problem? Please describe:**
It would be great to use the core functions with other plugins.

**Describe the solution you'd like:**
Seperate core functions as Node.js module and integrate it in this plugin.

**Describe alternatives you've considered:**

**Additional context:**

**Comment by hjdhjd** [comment]
I have no idea what this request is. 😄 Can you elaborate more specifically?

**Comment by 011V32** [comment]
It would be great if the core function of the plugin was outsourced to a separate module so that the core functions can also be used by other plugins.
(So pack the status generation, command interface etc. in an extra module, which is then used as a dependency in the Homebridge plugin. This means that other Homebridge plugins can also use these core functions.)
