### ISSUE TITLE
"stop" command is not being invoked

### ISSUE THREAD

**Issue by sixtyfive** [hjdhjd/homebridge-blinds-cmd#153]
f I understood the documentation correctly, with no status script and no status refresh interval, but a simulated transition duration being given, after, say, half of that duration (50% setting), the stop command should be invoked. this unfortunately never happens. the marquee keeps going down until it is fully closed, then up again until it is fully open. if i manually invoke the stop script somewhere in between, it stops immediately, so the stop script is not at fault.

**To Reproduce:**

- buy a raspberry pi
- buy an apple device
- install homebridge on the raspberry pi
- open HomeKit on the apple device and connect it to homebridge
- buy an old 1970s electrical marquee
- install it and let it open/close all the way noting down the duration that takes
- be a little annoyed it takes 2 seconds longer to close than to open ... curse at gravity
- buy something like a Sonoff Dual R3 and wire it up to your shiny new vintage 1970s marquee
- install homebridge-blinds-cmd
- write "open", "close" and "stop" scripts
- configure homebridge-blinds-cmd with the paths to those three scripts as well as the earlier-noted duration
- note that fully opening or closing the marquee works perfectly now (take care to prevent your kids from seeing you hit that button!)
- try a setting other than 0% or 100%, for example, 50%
- note that the marquee does not stop at 50% but again goes all the way up or down
- try invoking your stop script manually and not that the marquee immediately stops as requested

- for bonus points, tap the blinds icon on your apple device and note how after a few seconds it says "no response" despite the marquee moving perfectly fine and then note the HomeKit app restarting or something (but that's for another Issue, and I'm guessing not in this project)

**Logs:**

```
[11/04/2021, 22:46:17] [Blinds Command] Markise: Moving down from open to closed.
[11/04/2021, 22:46:17] [Blinds Command] Markise: Moving down from closed to open.
[11/04/2021, 22:46:17] [Blinds Command] Markise: Moving down from open to 93%.
[and so on]
```

**Homebridge Configuration:**

```json
{
    "accessories": [],
    "platforms": [
        {
            "name": "Config",
            "port": 8581,
            "platform": "config"
        },
        {
            "discovery": true,
            "devices": [
                {
                    "kind": "switch"
                }
            ],
            "platform": "SonoffDiyPlatform"
        },
        {
            "blinds": [
                {
                    "name": "Markise",
                    "up": "/home/pi/scripts/markise-hoch",
                    "down": "/home/pi/scripts/markise-runter",
                    "stop": "/home/pi/scripts/markise-stop",
                    "transitionInterval": 20,
                    "manufacturer": "Wissenwernich",
                    "model": "Grellgelb"
                }
            ],
            "platform": "Blinds Command"
        }
    ]
}
```

**Screenshots:**

**Environment:**

* **Homebridge Version:** v1.3.4
* **Node Version:** v14.16.0
* **Homebridge-Blinds-Cmd Plugin Version:** v3.1.0
* **Apple Device and iOS / macOS / iPadOS / tvOS Version:** don't know, don't care
* **Operating System and OS Version:** official Homebridge Raspberry Pi Image, which is Debian Buster

**Comment by sixtyfive** [comment]
You've got to be kidding me?

**Comment by sixtyfive** [comment]
Thank you, lovely bot.

**Comment by sixtyfive** [comment]
Last comment for fellow googlers: changed my own script to not make use of the "stop" and "transitionInterval" options, but calculating marquee state myself based on measured full transition time. Will unsubscribe here now for lack of response.

**Comment by hjdhjd** [comment]
It does work, given I use it daily.

**Comment by jimcrammond** [comment]
I know this is a long ago closed issue, but since I ran into this issue, I will explain the likely cause (user error) at least in my case. 

When the open/close scripts are run they are passed a number which is the target position. The target position is updated by the plugin to the number returned by these scripts. If a "close script" returns 0 it will therefore completely close the blind. The script is supposed to return the same number as passed in order to cause the stop script to be run. This is documented but not totally obvious.
