### ISSUE TITLE
No Reaction in HomeKit after adding a Blind

### ISSUE THREAD

**Issue by jelkose** [hjdhjd/homebridge-blinds-cmd#25]
**Describe The Problem:**
When I add a new blind via the Config UI the HomeKit app cannot connect to Homebridge anymore. It says "no reaction".
Also, if I try to add Homebridge (with configured blinds) as a new device in HomeKit it says: Device not compatible.
I can control the blinds via the Config UI anyway, so the configuration should be okay.
I've recently updated to iOS 14, maybe there is a change in the HomeKit app which causes this issue?

**To Reproduce:**
Install homebridge-blinds-cmd and add a blind via the Config UI.

**Logs:**

There is nothing showing up in the logs.

**Homebridge Configuration:**

```json
{
    "bridge": {
        "name": "Homebridge",
        "username": "",
        "port": ,
        "pin": ""
    },
    "devices": [],
    "subsection": [],
    "platforms": [
        {
            "name": "Config",
            "port": 8581,
            "auth": "form",
            "theme": "auto",
            "tempUnits": "c",
            "lang": "de",
            "sudo": true,
            "platform": "config"
        },
        {
            "name": "HomeMatic CCU",
            "ccu_ip": "",
            "subsection": "Homekit",
            "enable_hmip": false,
            "enable_wired": false,
            "ios10": true,
            "platform": "HomeMatic"
        },
        {
            "blinds": [
                {
                    "name": "Blinds Name",
                    "up": "/path/",
                    "down": "/path/",
                    "stop": "/path/"
                }
            ],
            "platform": "Blinds Command"
        }
    ],
    "accessories": []
}
```

**Environment:**

* **Homebridge Version**: 1.1.6 
* **Node Version**: v12.18.4 
* **Operating System and OS Version**:  Ubuntu Bionic Beaver (18.04.5 LTS)

**Comment by hjdhjd** [comment]
Hi there, thanks for the feedback. If you’re getting no response, I suspect that your blinds script isn’t returning the information needed. The script needs to return the status of the move once complete - you can look at the example scripts to see.

**Comment by jelkose** [comment]
Well the thing is, with configured blinds for the plugin I'm getting no response for all my devices. Seems like HomeKit can't even reach Homebridge anymore.
I built a script that returns a status anyway, but the problem perstists.

**Comment by hjdhjd** [comment]
If you have a way to reproduce the issue, please list the steps to create the problem and I’d be happy to take a look. I use this plugin daily without issue, so I’m curious as to what you’re running into.

**Comment by jelkose** [comment]
I've just made a clean install of homebridge and Homebridge-blinds-cmd on an Ubuntu 20.04 VM. Same behavior: As soon as I add a blind to the config, it says accessory not supported when trying to add it to HomeKit. When I add the blind after adding to HomeKit it looses connection.
Here is my test config:
```
{
    "bridge": {
        "name": "Homebridge",
        "username": "xxx",
        "port": 51735,
        "pin": "xxx"
    },
    "accessories": [],
    "platforms": [
        {
            "name": "Config",
            "port": 8581,
            "platform": "config"
        },
        {
            "blinds": [
                {
                    "name": "Test Blind",
                    "up": "echo 50",
                    "down": "echo 50"
                }
            ],
            "platform": "Blinds Command"
        }
    ]
}
```

**Comment by hjdhjd** [comment]
Please share the log files, the Homebridge version you are using, the plugin version you are using. The above isn't sufficient to figure out what's going on.

**Comment by hjdhjd** [comment]
I've been able to recreate this. Appreciate you reporting it...an update will be coming soon. Thanks again!

**Comment by jelkose** [comment]
Well I did not post the "normal" logs in the initial issue because there was nothing special in them. When running homebridge with ``DEBUG=*`` I can see just lots of nonsense without any line break. I could have shared this anyway.
But if You found the problem this becomes obsolete.
By the way: What was it?
Thanks a lot for Your support!

**Comment by hjdhjd** [comment]
Fixed in v3.0.5.

**Comment by hjdhjd** [comment]
When you write a plugin that's mostly for edge cases like mine, you don't get a lot of other people using it in the wild...so I don't expect people to not think the way I do. :smile:

Two issues - the one you called out, and another that I discovered by testing your use case:

1. Not supplying the blinds information (manufacturer, etc.) would cause things to fail.
2. Not handling the use case where someone removes a blind configuration.

**Comment by jelkose** [comment]
Good to know, thank You for the "look behind the scenes".
It works perfect for me right now!
