### ISSUE TITLE
Request to allow intermediate positions to be sent

### ISSUE THREAD

**Issue by basroovers** [hjdhjd/homebridge-blinds-cmd#4]
My roller shutters have 2 intermediate positions which would correspond to 98% opened (sun protection) and 50% opened.  I know the WindowCovering characteristics support a position parameter in the form of a percentage integer. To make this happen we would need to have split the percentages into blocks and round it.

This is how I think it would need to operate:
Homekit user sets blinds to 80%, it would execute the `up` command
Homekit user sets blinds to 60%, it would execute the `intermediate position 1` command
Homekit user sets blinds to 90%, it would execute the `intermediate position 2` command
Homekit user sets blinds to 100%, it would execute the `close` command

The last state would also need to be persisted like it is at the moment.

**Comment by hjdhjd** [comment]
Hmm. I understand the request...but to do this, you essentially need to have a really specific set of controls that you are using within HomeKit, probably in the form of a scene I imagine. I'll need to think about how to do this in a future version. I'd like to create a more general solution to this use case.
