### ISSUE TITLE
Move Function failed: /bin/sh: Not finding files

### ISSUE THREAD

**Issue by Alapied** [hjdhjd/homebridge-blinds-cmd#5]
So I've been trying to use the plugin to run a shell script that opens my homemade DIY blind motors, However, it keeps throwing a shell error: /bin/sh: 1: /home/pi/scripts/shellopen.sh: not found.  What do you suppose could be causing this? I have triple checked the directory and it exists and all my scripts are there. (Perms for running the files was an error accounted for earlier so I know that it can access the directory), also tried using python versions of my scripts to test that.
Any help would be appreciated 

plugin version  v1.1.0
homebridge version v1.10

Move function failed: /bin/sh: 1: /home/pi/scripts/shellopen.sh: not found

**Comment by Alapied** [comment]
Appears to maybe a PATH issue, similar to the issue described in  [this post](https://www.raspberrypi.org/forums/viewtopic.php?t=247337) ,not sure if this helps or not but I am not very advanced when it comes to software.

**Comment by hjdhjd** [comment]
It does sound like a path issue. Might also want to check that /bin/sh exists. Or if you’re using shebang...check the first line of your script. This is ultimately a path issue as you’ve surmised. If the path in your config.json is correct and absolute check:

1. Permissions for the relevant script.
2. The shebang in the script and ensure it’s valid.
3. Typos / errors in the script.

Good luck!

**Comment by Alapied** [comment]
Leaving a final comment to help with documentation (I have found a solution)

### The Shebang
Using the info above, I started researching more into what a shebang is, essentially for simple-minded people like me, it is a path to the runtime environment. Now I added shebangs in the form of #!/bin/bash as the script would be run using bash in the terminal. (however, just adding shebangs didn't work) This lead me thinking, a shebang is the path to the runtime similar to commands like bash/python/java etc that would be used to run a sh/py/jar file from the terminal then what if one used the absolute path to said script and environment? Well that works, in the terminal, one can use /bin/bash /home/pi/scripts/shellopen.sh (in my case) and this would be runnable from the terminal. The way this plugin operates as it takes whatever is in the config.json (upcmd: or downcmd:) and passes it into a terminal. so what if, I specify the path within the upcmd: "" command, well that worked, I was able to get my script to run 

### Final Solution
changing these lines from this:
"up_cmd": " /home/pi/scripts/shellopen.sh",
to this
"up_cmd": "/bin/bash /home/pi/scripts/shellopen.sh",
got the script to run

Note: Even works with python and other environment scripts, just change shebang and the path
 eg:(/usr/bin/python)

Cheers for your help

**Comment by hjdhjd** [comment]
Anytime. Yes, the above will work..but that’s a bit of an extreme, though perfectly legitimate solution.

My guess is the core problem you have is not setting the right permissions on your script to be able to execute.

For the manual for the command to adjust permissions, type in: `man chmod` 

To set the right permissions (this is a bit too permissive but fine for home configs):

`chmod a+rx /path/to/your/script`

Then adjust up_cmd to be /path/to/your/script and all should work.

Or...you can leave it as-is. It’s up to you. Admittedly this plugin expects a modicum of scripting knowledge, but I appreciate you highlighting that!
