### ISSUE TITLE
Blinds not Responding after new Update and specific State to open never worked

### ISSUE THREAD

**Issue by hauni97** [hjdhjd/homebridge-blinds-cmd#81]
I have Python MQTT scripts (with the paho plugin) opening pausing and closing my blinds.

Since the new plug-in version, it gives me a "No Response" error on the home kit app. And I have tried to play around with the status files, which did not work or stop the blinds in the correct state. I do not understand the provided sample script in the plug-in as I use MQTT.

Looking forward to some advice to the developer rather than rolling back a version, as I would like to use the feature to stop the blinds at any desired state and could not remove the "stop" button in the previous plug-in version.

**Issue Reproduction:**
To reproduce the issue I am opening and closing the blinds. 

**Logs:**
[time] [Blinds Command] Invalid value returned when executing command python /var/lib/homebridge/Peters_Pause.py 5: NaN. A numeric value between 0 and 100 is expected.

**Homebridge Configuration:**

```json
        {
            "blinds": [
                {
                    "name": "Peters Blinds",
                    "up": "python /var/lib/homebridge/Peters_Blinds_UP.py",
                    "down": "python /var/lib/homebridge/Peters_Blinds_DOWN.py",
                    "stop": "python /var/lib/homebridge/Peters_Blinds_Pause.py",
                    "status": "python /var/lib/homebridge/Peters_Status-File.py",
                    "transitionInterval": 27,
                    "refreshRate": 5
                },
....
```
**Python Scripts:**
Below are both scripts for closing the blinds.

Initial script before the new CMD blinds version, to close the blinds:
```py
import paho.mqtt.client as mqtt

#Copyright

client = mqtt.Client()
client.username_pw_set(username=“username”, password=“password”)
client.connect(“broker”, port, no)
client.publish(“topic”, “command _to_close_blinds);
client.disconnect();
FILE = open(“Status_File.txt”, "wt")
FILE.write("0")
FILE.close()
```
Attempted script version since new update to get 
```py
import paho.mqtt.client as mqtt

#Copyright

client = mqtt.Client()
client.username_pw_set(username=“username”, password=“password”)
client.connect(“broker”, port, no)
client.publish(“topic”, “command _to_close_blinds);
client.disconnect();
FILE = open("Status_File.txt", "wt")


def func(n):
    FILE = open("Status.txt", "wt")
    FILE.write(str(n))
    print(n)


for i in range(5, 105, 5):
    func(i)
    sleep(1)
    FILE.close()
FILE.close()
```

Closing the blinds are just reversed and with an MQTT closing command.

The following shows the status read:
```py
FILE = open("Status.txt", "r")
print(FILE.read())
FILE.close()
```
I set the status initially to "100" for open and "0" to close, as it was the only one status that worked. Would be grateful if anyone could help me to solve the issue to open the blinds to a specific state such as "30" and get rid of the home kit message of "No response."
The blinds still open and close normally bit give me an error with Siri and the home app as shown. 

**Screenshots:**
This is what is displayed for both script versions since plugin version 3.1.0 (2020-11-30):
![IMG_24BB0C44ABC8-1 (1)](https://user-images.githubusercontent.com/37558304/103139746-4b4a3700-46d7-11eb-8e09-928d451450fd.png )

**Environment:**

* **Homebridge Version:** v1.1.7
* **Node Version:** v12.18.4
* **Homebridge-Blinds-Cmd Plugin Version:** v3.1.0
* **Apple Device and iOS Version:** iPhone IOS 14.3
* **Operating System and OS Version:** Raspberry Pi 4

**Comment by hauni97** [comment]
The plugin homebridge-blinds v1.3.23-beta.1 with the added command line feature is currently the perfect solution to this.

**Comment by hjdhjd** [comment]
@hauni97 Apologies - been a bit focused elsewhere. Did you get the answers you were looking for?

**Comment by hjdhjd** [comment]
The key is in what is returned by the status script. I suspect your No Response issues stem from that. `homebridge-blinds-cmd` will call the status script with what it *believes* the status to be. So:

`status-script 60`

for instance. What it's saying to you is "I'm asking you for a status update, but I think the blind status is 60%, is that correct?"

The status script should output what is the canonical status. It can be as simple as outputting the status number that is passed into the script, effectively confirming what `homebridge-blinds-cmd` believes is the status. Or, it can query the blind directly if it has a way to do so (via an API, etc.) and output that value.

When the status script outputs nothing, that's where you run into issues.

Does that help?

**Comment by hjdhjd** [comment]
Oh...and Python is not my jam, so if you want help troubleshooting a Python script, you'll have to look elsewhere I'm afraid. :smile:

**Comment by dxdc** [comment]
@hjdhjd I tried to reference the details in #82 but it was auto-closed. Wanted to see if you'd be interested in reviewing functionality. I've put a lot of work into http-blinds since you originally forked it.

**Comment by hjdhjd** [comment]
@dxdc Thanks for reaching out. I'll take a look at some point in the next couple of weeks, and happy to provide some feedback. Thanks!

**Comment by hjdhjd** [comment]
@hauni97 I see you got things going it seems with homebridge-blinds. Terrific to hear it, it's a fine plugin. You may want to account for edge cases in status. That's *why* a status command is so essential to really do this in a comprehensive manner that survives reality. :smile:

See https://github.com/hjdhjd/homebridge-blinds-cmd/issues/82#issuecomment-751525030 for more specifics.

As homebridge-blinds is currently configured, you're basically counting on it being 100% correct on the status of a blind. In practice, people manually shift blinds outside of HomeKit all the time. You need some reasonable way to account for that status. It's why a status command is essential if you want to account for things in a holistic manner.

**Comment by dxdc** [comment]
> As homebridge-blinds is currently configured, you're basically counting on it being 100% correct on the status of a blind. In practice, people manually shift blinds outside of HomeKit all the time. You need some reasonable way to account for that status. It's why a status command is essential if you want to account for things in a holistic manner.

See `position_url` in config which accounts for status (0-100).

**Comment by hauni97** [comment]
@hjdhjd I get your point but I have blinds on a Hz frequency not giving any feedback of its status at all if used outside of HomeKit. I basically used and programmed an ES8266 to emit signals received by an MQQT broker with a python script sending to the broker my desired message (action). 
Therefore I cannot input any status outside of HK as a Hz frequency does not support it.
And if I have no real status a plugin requiring a status is hard to use.

I agree user interfaces and the documentation could be simpler. 

Regarding the status, the blinds command seems to support the position of the current blind (0- 100).
See below in the GUI of the homebridge-blinds-cmd plugin.

<img width="760" alt="Screen Shot 2020-12-28 at 12 08 07 AM" src="https://user-images.githubusercontent.com/37558304/103181391-d4f93080-48a0-11eb-9755-70603acb848d.png">

**Comment by hjdhjd** [comment]
@hauni97 The plugin doesn't require status to function. :smile: More to the point, you can easily supply status by following the steps above and simply validating the status that the plugin is communicating, thereby making it the canonical status.

Specifically: the status script will be called with what `homebridge-blinds-cmd` believes the status to be. If all your script did was return that same number, you're set.

Setting position isn't the issue, it's reporting the current position that's an unsolved edge case in `homebridge-blinds`...and it's an important one if your blinds can be controlled outside of HomeKit (aka my use case!).

Thanks and good luck!
