### ISSUE TITLE
Exit code 255 with scripts

### ISSUE THREAD

**Issue by DEA156** [hjdhjd/homebridge-blinds-cmd#95]
**Describe The Problem:**
Homebridge loads the homebridge-blinds-cmd plugin but has a problem working with the script files. Homebridge not able to execute scripts. I am using somfy.pl.

When I execute somfy.pl from the command line, it works perfectly. For example, this makes the shade go up:
$./somfy.pl 1 up

**To Reproduce:**
Start Homebridge and try to change the state of a shade.

**Logs:**
This is the error:
"Error executing the command: Command failed with exit code 255: <path to my script.pl>"
It also prints the output of "die $USAGE".

![image](https://user-images.githubusercontent.com/54457944/104794836-83d5b180-5767-11eb-95d6-af11b0e6fcf6.png)

* **Homebridge Version:** 1.1.7
* **Node Version:** 14.15.4
* **Homebridge-Blinds-Cmd Plugin Version:** 3.1.0
* **Operating System and OS Version:** Raspbian

**Comment by hjdhjd** [comment]
Based on the error message, I'm guessing the command you entered in the configuration is slightly off...can you show me the relevant portion of your Homebridge config.json?

**Comment by DEA156** [comment]
Sure, here is the homebridge-blinds-cmd section of my config.json:

![image](https://user-images.githubusercontent.com/54457944/104859680-392d7400-58e4-11eb-93f7-aa43e683b76a.png)

**Comment by hjdhjd** [comment]
There’s your problem. :smile:

The command line specified is what is executed - literally. If you intend to pass a script arguments, you need to specify them.

So “up” for instance: 

```
“/home/pi/Documents/somfy/somfyscript.pl 1 up”
```

**Comment by DEA156** [comment]
Well I'll be damned. That was the problem. Thank you!

Note (for anyone else coming down this path): make sure the state files have r+w permissions for homebridge or else homebridge won't be able to update those files.
