### ISSUE TITLE
Question about intermediate positions

### ISSUE THREAD

**Issue by DEA156** [hjdhjd/homebridge-blinds-cmd#97]
**Describe The Problem:**
I'm looking for some clarification on how the plugin handles intermediate shade positions. Let's say the shade is closed and I want to open it halfway. The transitionInterval is set to the appropriate duration, in my case 25 seconds. If I tell HomeKit to open the shade halfway, will the plugin execute the stop script when the shade reaches 50%? Currently, requests for intermediate positions result in the shade moving to an all-open or all-closed position, so it seems like the plugin isn't activating the stop script.

**To Reproduce:**
Ask Siri to open the shades halfway.

**Logs:**

In the screenshot below the shade was closed and I asked Siri to open the shade halfway. The log shows the shade stopping at 50%, but the shade actually opened all the way.

<img width="759" alt="Screen Shot 2021-01-18 at 8 11 17 PM" src="https://user-images.githubusercontent.com/54457944/104983323-ceeeff00-59c9-11eb-8d13-8b0161e89d1e.png">

**Homebridge Configuration:**

<img width="515" alt="Screen Shot 2021-01-18 at 8 11 46 PM" src="https://user-images.githubusercontent.com/54457944/104983382-ea5a0a00-59c9-11eb-83ea-7f05b59bc182.png">

**Screenshots:**

**Environment:**

* **Homebridge Version:**  v1.1.7
* **Node Version:**  v14.15.4
* **Homebridge-Blinds-Cmd Plugin Version:** v3.1.0
* **Apple Device and iOS / macOS / iPadOS / tvOS Version:** iOS 14.3
* **Operating System and OS Version:** 
Raspbian

**Comment by hjdhjd** [comment]
Yes, it will!

**Comment by DEA156** [comment]
You are right, it clearly works. The somfy-bond script has capabilities the somfy script does not. On a side note, when calibrating the transitionInterval to get a blind to stop at the halfway point I noticed that the interval needs to be reduced or else the blind will move too far. I think there is a subtle delay in the stop command that must be factored in with trial and error testing. Thank you for writing and maintaining this wonderful plugin!

**Comment by hjdhjd** [comment]
Your welcome! And it’s definitely trial and error. :smile:

Such is the joy of trying to emulate functionality than one would hope would just exist with all these fancy blinds!
